import type { ExampleDefinition } from './schema';

export const DOC5_PACKAGE = {
  name: 'apexify.js',
  version: '6.0.0',
  commit: 'dbed9743353593eafae9a7b1c25312d7170a233b',
} as const;

export const exampleDefinitions = [
  {
    id: 'node.canvas.basic',
    title: 'Create a deterministic canvas',
    summary: 'Render a fixed 320×180 server-side PNG using the public ApexPainter canvas API.',
    runtime: 'node',
    difficulty: 'minimal',
    packages: ['apexify.js'],
    features: ['canvas', 'output'],
    apiSymbols: ['apexify.js::ApexPainter', 'apexify.js::ApexPainter#createCanvas'],
    sourceFiles: ['examples/node/canvas-basic/index.ts'],
    entrypoint: 'examples/node/canvas-basic/index.ts',
    outputType: 'image',
    expectedOutput: [{ path: 'canvas-basic.png', kind: 'png', public: true, verificationMode: 'metadata', width: 320, height: 180, minBytes: 100, maxBytes: 2_000_000 }],
    verification: { typecheck: true, executable: true, timeoutMs: 20_000, stderrPolicy: 'fail-on-error-pattern' },
    relatedDocs: ['/docs/node/canvas'],
    relatedExamples: ['node.integration.report'],
    gallery: { enabled: true, featured: true, previewOutput: 'canvas-basic.png' },
    explanation: {
      goal: 'Create the smallest useful server-rendered image with explicit dimensions and background color.',
      prerequisites: ['Node.js 22, 24, or 26', 'apexify.js 6.0.0'],
      importantOptions: ['width', 'height', 'colorBg'],
      whyOptions: ['Explicit dimensions make output verification deterministic.', 'A local color background avoids remote assets and font dependencies.'],
      variants: ['Replace colorBg with a gradient or layered background after the basic pipeline is understood.'],
      performanceNote: 'The example uses one small canvas and performs no remote I/O.',
      errorNote: 'Invalid dimensions are rejected by Apexify.js runtime validation before rendering.',
      nextStep: 'Use node.chart.bar for a generated chart or node.integration.report for a multi-file workflow.',
    },
  },
  {
    id: 'node.chart.bar',
    title: 'Render a bar chart',
    summary: 'Render a practical bar chart as a verified 480×320 PNG through ApexPainter.createChart().',
    runtime: 'node',
    difficulty: 'practical',
    packages: ['apexify.js'],
    features: ['charts', 'canvas', 'output'],
    apiSymbols: ['apexify.js::ApexPainter', 'apexify.js::ApexPainter#createChart'],
    sourceFiles: ['examples/node/chart-bar/index.ts'],
    entrypoint: 'examples/node/chart-bar/index.ts',
    outputType: 'image',
    expectedOutput: [{ path: 'chart-bar.png', kind: 'png', public: true, verificationMode: 'metadata', width: 480, height: 320, minBytes: 500, maxBytes: 4_000_000 }],
    verification: { typecheck: true, executable: true, timeoutMs: 25_000, stderrPolicy: 'fail-on-error-pattern' },
    relatedDocs: ['/docs/getting-started'],
    relatedExamples: ['node.integration.report'],
    gallery: { enabled: true, previewOutput: 'chart-bar.png' },
    explanation: {
      goal: 'Turn structured bar data into a server-generated chart image.',
      prerequisites: ['Node.js 22, 24, or 26', 'apexify.js 6.0.0'],
      importantOptions: ['chart type: bar', 'dimensions.width', 'dimensions.height'],
      whyOptions: ['A fixed chart type keeps the example focused.', 'Explicit dimensions allow PNG metadata verification without pixel-fragile golden tests.'],
      variants: ['Use the same createChart API with pie, line, scatter, radar, horizontalBar, or polarArea data shapes.'],
      performanceNote: 'Chart rendering is CPU-bound and local; this example intentionally uses three bars.',
      errorNote: 'Malformed chart data or non-finite numeric input is rejected by Apexify.js validation.',
      nextStep: 'Combine rendered output with application metadata as shown in node.integration.report.',
    },
  },
  {
    id: 'node.gif.basic',
    title: 'Generate a two-frame GIF',
    summary: 'Generate a tiny server-side GIF from two Apexify canvas frames and verify its GIF structure.',
    runtime: 'node',
    difficulty: 'advanced',
    packages: ['apexify.js'],
    features: ['gif', 'canvas', 'media', 'output'],
    apiSymbols: ['apexify.js::ApexPainter', 'apexify.js::ApexPainter#createCanvas', 'apexify.js::ApexPainter#createGIF'],
    sourceFiles: ['examples/node/gif-basic/index.ts'],
    entrypoint: 'examples/node/gif-basic/index.ts',
    outputType: 'gif',
    expectedOutput: [
      { path: 'animation.gif', kind: 'gif', public: true, verificationMode: 'structural', width: 96, height: 64, minBytes: 100, maxBytes: 4_000_000 },
      { path: 'poster.png', kind: 'png', public: true, verificationMode: 'metadata', width: 96, height: 64, minBytes: 100, maxBytes: 2_000_000 },
    ],
    verification: { typecheck: true, executable: true, timeoutMs: 30_000, stderrPolicy: 'fail-on-error-pattern' },
    relatedDocs: ['/docs/getting-started'],
    gallery: { enabled: true, previewOutput: 'poster.png' },
    explanation: {
      goal: 'Prove the current server-side GIF encoder using small deterministic local frames.',
      prerequisites: ['Node.js 22, 24, or 26', 'apexify.js 6.0.0'],
      importantOptions: ['outputFormat', 'width', 'height', 'repeat', 'quality'],
      whyOptions: ['Buffer output keeps verification inside the fixture.', 'Small dimensions and two frames keep CI cost bounded.', 'The Gallery uses the verified poster by default so reduced-motion users are not forced to watch animation.'],
      variants: ['Increase frame count or use generated-frame mode for real animation workflows.'],
      performanceNote: 'GIF encoding is heavier than a single PNG, so the completion example is intentionally tiny.',
      errorNote: 'Missing frame data, invalid dimensions, or frame-limit violations fail the run.',
      nextStep: 'Use production-sized inputs only after measuring frame count, dimensions, and encoding quality.',
    },
  },
  {
    id: 'node.integration.report',
    title: 'Build a multi-file chart report',
    summary: 'Use a typed data module plus ApexPainter to generate both a report chart and exact JSON summary.',
    runtime: 'node',
    difficulty: 'integration',
    packages: ['apexify.js'],
    features: ['charts', 'output', 'batch'],
    apiSymbols: ['apexify.js::ApexPainter', 'apexify.js::ApexPainter#createChart'],
    sourceFiles: ['examples/node/integration-report/index.ts', 'examples/node/integration-report/report-data.ts'],
    entrypoint: 'examples/node/integration-report/index.ts',
    outputType: 'multi',
    expectedOutput: [
      { path: 'report.png', kind: 'png', public: true, verificationMode: 'metadata', width: 640, height: 360, minBytes: 500, maxBytes: 5_000_000 },
      { path: 'summary.json', kind: 'json', public: false, verificationMode: 'semantic', jsonEquals: { total: 180, highest: 'Docs', entries: 3 } },
    ],
    verification: { typecheck: true, executable: true, timeoutMs: 30_000, stderrPolicy: 'fail-on-error-pattern' },
    relatedDocs: ['/docs/getting-started', '/docs/node/canvas'],
    relatedExamples: ['node.chart.bar'],
    gallery: { enabled: true, featured: true, previewOutput: 'report.png' },
    explanation: {
      goal: 'Prove a realistic multi-file example that produces more than one independently validated output.',
      prerequisites: ['Node.js 22, 24, or 26', 'apexify.js 6.0.0'],
      importantOptions: ['bar chart data', 'dimensions'],
      whyOptions: ['Data lives in a separate typed module to prove multi-file fixture copying.', 'The PNG uses metadata verification while the JSON summary uses exact semantic verification.'],
      variants: ['Replace the report data module with application data while retaining the same rendering boundary.'],
      performanceNote: 'The fixture creates one 640×360 chart and one tiny JSON file; no remote resources are loaded.',
      errorNote: 'Type errors in the imported data module fail before execution; output contract mismatches fail after execution.',
      nextStep: 'Link the same stable example identity from feature guides and API reference metadata.',
    },
  },
] as const satisfies readonly ExampleDefinition[];
