import fs from 'node:fs';
import path from 'node:path';
import { DOC3_REQUIRED_COMPONENTS } from '../../components/mdx/doc3-contract';
const ROOT=process.cwd();const read=(relative:string)=>fs.readFileSync(path.join(ROOT,relative),'utf8');const fail=(message:string):never=>{throw new Error(`[doc3-verify] ${message}`);};
const rich=read('components/mdx/RichDocsComponents.tsx');const route=read('components/docs/route/RouteDocsMarkdown.tsx');const parser=read('components/mdx/rich-parser.ts');const index=read('components/mdx/index.tsx');const alert=read('components/mdx/Alert.tsx');const dropdown=read('components/mdx/Dropdown.tsx');const codeSwitcher=read('components/mdx/CodeSwitcher.tsx');
for(const name of DOC3_REQUIRED_COMPONENTS){const implemented=name==='Tabs'?rich.includes('export { Tabs };'):rich.includes(`function ${name}`);if(!implemented)fail(`${name} is not implemented by RichDocsComponents`);if(!route.includes(`case '${name}'`))fail(`${name} is not wired into the routed renderer`);}
if(!index.includes("export * from './RichDocsComponents'"))fail('component barrel does not expose DOC-3 components');if(!parser.includes('JSON.parse'))fail('safe JSON expression parser is missing');if(/eval\s*\(|new Function/.test(parser+route))fail('arbitrary JavaScript evaluation is forbidden');if(alert.includes("'use client'"))fail('Alert compatibility wrapper should be server-safe');if(dropdown.includes("'use client'"))fail('Dropdown compatibility wrapper should be server-safe');if(!dropdown.includes('<Details'))fail('Dropdown must enhance/reuse native Details');if(!codeSwitcher.includes('<Tabs'))fail('CodeSwitcher must enhance/reuse Tabs');if(fs.existsSync(path.join(ROOT,'components/mdx/MDXRenderer.tsx')))fail('obsolete overlapping components/mdx/MDXRenderer.tsx must be removed');
const pages=[read('content/docs/03-feature-guides/canvas/00-create-canvas-overview.mdx'),read('content/docs/03-feature-guides/canvas/01-canvas-size-and-coordinates.mdx')];const union=pages.join('\n');for(const required of ['Callout','Steps','CodeGroup','ComparisonTable','FeatureMatrix','DecisionGuide','ArchitectureDiagram','Details','AvailabilityMatrix','BeforeAfter','CodeBlockV2','CodeDiff','InstallCommand','ExampleCard','OutputPreview','NextSteps']){if(!union.includes(`<${required}`))fail(`representative guide/reference proof does not exercise ${required}`);}for(const page of pages){if(!/^---[\s\S]*?slug:/m.test(page))fail('representative page lost DOC-1 frontmatter');}
console.log(`[doc3-verify] PASS — ${DOC3_REQUIRED_COMPONENTS.length} required components implemented and routed; representative guide/reference pages exercise the reusable authoring path`);
