import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { expandSearchAliases } from '../../lib/search/aliases';
import { allGalleryItemsForDocs, plainGalleryDescription } from '../../lib/gallery/docs/galleryRegistry';
import { galleryDeepLink } from '../../lib/gallery/core/galleryDocLink';
import { normalizeSearchText, searchRecords, tokenizeSearchText } from '../../lib/search/query';
import { SEARCH_SCHEMA_VERSION, type SearchIndexArtifact, type SearchRecord, type SearchRecordKind } from '../../lib/search/schema';

const ROOT=process.cwd(), OUT=path.join(ROOT,'generated','docs-doc6'), CHECK=process.argv.includes('--check');
const START='61f690695be11de1928e0ee028c65fd0496be76c', PHASE14P='5d9b71f185140d6c3477286b8fb111f293e52b48';
const readJson=<T=any>(p:string)=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8')) as T;
const readText=(p:string)=>fs.readFileSync(path.join(ROOT,p),'utf8').replace(/\r\n/g,'\n');
const hash=(v:string|Buffer)=>crypto.createHash('sha256').update(v).digest('hex');
const stable=(v:unknown)=>`${JSON.stringify(v,null,2)}\n`;
const write=(name:string,v:unknown)=>{const p=path.join(OUT,name),s=stable(v);if(CHECK){if(!fs.existsSync(p)||fs.readFileSync(p,'utf8')!==s)throw new Error(`[doc6] stale ${name}`);}else{fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(p,s);}};
const uniq=(xs:Array<string|undefined|null>)=>[...new Set(xs.filter((x):x is string=>Boolean(x?.trim())).map(x=>x.trim()))];
const runtimes=(xs:string[]=[])=>(uniq(xs.map(x=>/^node\d+$/i.test(x)?'node':x)).sort());
const strip=(s:string)=>s.replace(/^---[\s\S]*?---\s*/m,'').replace(/```[\s\S]*?```/g,' ').replace(/<[^>]+>/g,' ').replace(/\{#[^}]+\}/g,' ').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[`*_~>|]/g,' ').replace(/\s+/g,' ').trim();
const cut=(s:string,n=240)=>{const x=strip(s);return x.length>n?`${x.slice(0,n-1).trimEnd()}…`:x;};
const headings=(body:string)=>body.split('\n').map(line=>/^(#{1,4})\s+(.+?)(?:\s+\{#([^}]+)\})?\s*$/.exec(line.trim())).filter(Boolean).map((m:any)=>({level:m[1].length,text:m[2].replace(/[`*_~]/g,'').trim(),id:(m[3]||m[2].toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')).trim()})).filter((h:any)=>h.id&&h.text);
const titleFrom=(body:string,id:string)=>headings(body)[0]?.text||id.replace(/^\d+-/,'').split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' ');
const slug=(v:string)=>v.replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase();

const docs=readJson<any>('generated/docs-doc1/docs-manifest.json');
const redirects=readJson<any>('generated/docs-doc1/redirect-manifest.json');
const api=readJson<any>('generated/docs-doc4/api-manifest.json');
const examples=readJson<any>('generated/docs-doc5/example-manifest.json');
const docsBySource=new Map((docs.pages??[]).map((p:any)=>[p.sourcePath,p]));
const sourcePaths=uniq(['generated/docs-doc1/docs-manifest.json','generated/docs-doc1/navigation-manifest.json','generated/docs-doc1/redirect-manifest.json','generated/docs-doc4/api-manifest.json','generated/docs-doc5/example-manifest.json','lib/gallery/docs/galleryRegistry.ts','lib/gallery/docs/doc5GalleryAdapter.ts','lib/gallery/core/galleryDocLink.ts',...(redirects.legacyDocuments??[]).map((x:any)=>x.sourcePath)]).sort();
const sourceFiles=sourcePaths.map(p=>{const b=fs.readFileSync(path.join(ROOT,p));return{path:p,sha256:hash(b),bytes:b.length};});
const galleryData=allGalleryItemsForDocs.map((x:any)=>({id:x.id,title:x.title,description:x.description,category:x.category,featured:Boolean(x.featured),thumbnail:x.thumbnail??null}));
const gallerySha=hash(stable(galleryData)), sourceChecksum=hash(stable({sourceFiles,gallerySha}));

const records:SearchRecord[]=[];const ids=new Set<string>();
function add(r:SearchRecord){if(ids.has(r.id))return;if(!r.title.trim()||!r.canonicalHref)throw new Error(`[doc6] invalid record ${r.id}`);ids.add(r.id);records.push({...r,breadcrumb:uniq(r.breadcrumb),runtime:runtimes(r.runtime),packages:uniq(r.packages).sort(),keywords:uniq(r.keywords),aliases:uniq(r.aliases),goals:uniq(r.goals)});}
const stop=new Set(['the','and','for','with','that','this','from','are','you','your','can','not','but','into','use','using','when','where','what','how','its','all','any','has','have','will','then','than','also','only','each','per','via']);
for(const entry of redirects.legacyDocuments??[]){
 const body=readText(entry.sourcePath), page:any=docsBySource.get(entry.sourcePath), id=entry.identity, href=page?.canonicalPath??entry.target, title=page?.title??titleFrom(body,id), category=page?.category??entry.sourcePath.split('/').slice(2,-1).join(' / '), rt=page?.runtime??['node'], pkg=page?.package??api.package.name, stability=page?.stability??'CURRENT';
 const bodyTerms=tokenizeSearchText(strip(body)).filter(t=>t.length>=3&&!stop.has(t));const kw=expandSearchAliases(uniq([...(page?.keywords??[]),page?.feature,...tokenizeSearchText(title),...bodyTerms]));
 const kind:SearchRecordKind=entry.sourcePath.endsWith('/changelog.mdx')?'changelog':'doc';
 add({id:`doc:${id}`,kind,title,description:page?.description??cut(body,180),excerpt:cut(body),href,canonicalHref:href,breadcrumb:['Docs',category,title],runtime:rt,packages:[pkg],stability,version:page?.since??api.package.version,domain:page?.feature??category,keywords:kw,aliases:uniq([...(page?.aliases??[]),...(page?.legacyHashes??[])]),goals:uniq([page?.description,title]),sourceId:id,sourcePath:entry.sourcePath});
 for(const h of page?.headings??headings(body)){const hh=page?.canonicalPath?`${page.canonicalPath}#${h.id}`:`${entry.target}?h=${encodeURIComponent(h.id)}`;add({id:`heading:${id}:${h.id}`,kind:'heading',title:h.text,description:`Heading in ${title}`,href:hh,canonicalHref:hh,breadcrumb:['Docs',title,h.text],runtime:rt,packages:[pkg],stability,version:page?.since??api.package.version,domain:page?.feature??category,keywords:expandSearchAliases(uniq([...kw,h.text])),aliases:[],goals:[],sourceId:id,sourcePath:entry.sourcePath});}
}

const apiHref=new Map<string,string>();
for(const s of api.symbols??[]){apiHref.set(s.id,s.href);for(const m of s.members??[])apiHref.set(m.id,m.href);}
for(const s of api.symbols??[]){
 add({id:`api-symbol:${s.id}`,kind:'api-symbol',title:s.symbol,description:s.summary,href:s.href,canonicalHref:s.href,breadcrumb:['API Reference',s.symbol],runtime:runtimes(s.runtimeTargets),packages:[s.package??api.package.name],stability:s.stability,version:s.since??api.package.version,domain:s.kind,symbol:s.symbol,keywords:expandSearchAliases(uniq([s.symbol,s.kind,s.signature,...(s.exportPaths??[])])),aliases:uniq(s.exportPaths??[]),goals:uniq([s.summary]),sourceId:s.id,sourcePath:s.source?.sourcePath});
 for(const m of s.members??[]){
  add({id:`api-member:${m.id}`,kind:'api-member',title:`${m.owner}.${m.name}`,description:m.summary,href:m.href,canonicalHref:m.href,breadcrumb:['API Reference',s.symbol,m.name],runtime:runtimes(m.runtimeTargets),packages:[s.package??api.package.name],stability:m.stability,version:m.since??s.since??api.package.version,domain:s.symbol,symbol:`${m.owner}.${m.name}`,keywords:expandSearchAliases(uniq([m.name,m.owner,m.signature])),aliases:[m.name],goals:uniq([m.summary]),sourceId:m.id,sourcePath:m.source?.sourcePath});
  const seen=new Set<string>();const visit=(o:any)=>{if(seen.has(o.id))return;seen.add(o.id);const oh=`${m.href}#option-${slug(o.path)}`;add({id:`api-option:${o.id}`,kind:'api-option',title:o.path,description:o.description,href:oh,canonicalHref:oh,breadcrumb:['API Reference',s.symbol,m.name,'Options',o.path],runtime:runtimes(o.runtimeTargets??m.runtimeTargets),packages:[s.package??api.package.name],stability:o.stability??m.stability,version:m.since??s.since??api.package.version,domain:s.symbol,optionPath:o.path,keywords:expandSearchAliases(uniq([o.path,o.name,o.type?.text,...(o.allowedValues??[]).map(String)])),aliases:uniq([o.name]),goals:uniq([o.description]),sourceId:o.id,sourcePath:o.source?.sourcePath});for(const c of o.children??[])visit(c);};
  for(const ov of m.overloads??[])for(const p of ov.parameters??[])for(const o of p.options??[])visit(o);
 }
}
for(const t of api.types??[]){add({id:`api-type:${t.id}`,kind:'api-type',title:t.name,description:`Public type ${t.name}`,href:t.href,canonicalHref:t.href,breadcrumb:['API Reference','Types',t.name],runtime:['node'],packages:[api.package.name],stability:'CURRENT',version:api.package.version,domain:'types',typeName:t.name,keywords:expandSearchAliases(uniq([t.name,t.type?.text])),aliases:[],goals:[],sourceId:t.id,sourcePath:t.source?.sourcePath});}
for(const e of api.errors??[]){const base=(e.relatedApiIds??[]).map((id:string)=>apiHref.get(id)).find(Boolean)??'/api-reference';const href=`${base}#errors`;add({id:`error:${e.id}`,kind:e.code?'diagnostic':'error',title:e.code?`${e.code} · ${e.className}`:e.className,description:`${e.condition} ${e.resolution}`.trim(),href,canonicalHref:href,breadcrumb:['API Reference','Errors',e.className],runtime:runtimes(e.runtimeTargets),packages:[api.package.name],stability:'CURRENT',version:api.package.version,domain:'errors',errorCode:e.code,keywords:expandSearchAliases(uniq([e.code,e.className,e.condition,e.resolution])),aliases:uniq([e.code]),goals:uniq([e.condition,e.resolution]),sourceId:e.id});}

const exampleIds=new Set<string>();
for(const e of examples.examples??[]){exampleIds.add(e.id);add({id:`example:${e.id}`,kind:'example',title:e.title,description:e.summary,excerpt:e.explanation?.goal,href:e.canonicalRoute,canonicalHref:e.canonicalRoute,breadcrumb:['Examples',e.runtime,e.title],runtime:[e.runtime],packages:e.packages??[api.package.name],stability:'CURRENT',version:e.verifiedPackageVersion??api.package.version,domain:(e.features??[])[0]??'examples',symbol:(e.apiSymbols??[])[0],keywords:expandSearchAliases(uniq([...(e.features??[]),...(e.apiSymbols??[]),e.difficulty,e.outputType,e.explanation?.goal])),aliases:uniq(e.relatedExamples??[]),goals:uniq([e.summary,e.explanation?.goal,e.explanation?.nextStep]),sourceId:e.id});}
for(const g of allGalleryItemsForDocs as any[]){if(exampleIds.has(g.id))continue;const href=galleryDeepLink(g);add({id:`gallery:${g.id}`,kind:'gallery',title:g.title,description:plainGalleryDescription(g.description??''),href,canonicalHref:href,breadcrumb:['Gallery',String(g.category??'Examples'),g.title],runtime:['node'],packages:[api.package.name],stability:'CURRENT',version:api.package.version,domain:String(g.category??'gallery'),keywords:expandSearchAliases(uniq([g.title,g.category,plainGalleryDescription(g.description??'',300)])),aliases:[],goals:uniq([plainGalleryDescription(g.description??'',180)]),sourceId:g.id});}
records.sort((a,b)=>a.id.localeCompare(b.id));

const tokens=Object.create(null) as Record<string,string[]>;
const prefixes=Object.create(null) as Record<string,string[]>;
for(const r of records){const values=[r.title,r.description,r.excerpt,r.symbol,r.optionPath,r.typeName,r.errorCode,...r.keywords,...r.aliases,...r.goals,...r.runtime,...r.packages].filter(Boolean).join(' ');for(const t of tokenizeSearchText(values)){(tokens[t]??=[]).push(r.id);const p=t.slice(0,Math.min(6,t.length));(prefixes[p]??=[]).push(r.id);}}
for(const map of [tokens,prefixes])for(const k of Object.keys(map))map[k]=[...new Set(map[k])].sort();
const index:SearchIndexArtifact={schemaVersion:SEARCH_SCHEMA_VERSION,sourceChecksum,recordCount:records.length,tokens,prefixes};

const count=(kind:SearchRecordKind)=>records.filter(r=>r.kind===kind).length;
const optionTotal=(api.symbols??[]).flatMap((s:any)=>s.members??[]).reduce((n:number,m:any)=>{const seen=new Set<string>();const visit=(o:any)=>{seen.add(o.id);for(const c of o.children??[])visit(c)};for(const ov of m.overloads??[])for(const p of ov.parameters??[])for(const o of p.options??[])visit(o);return n+seen.size;},0);
const galleryAccounted=(examples.examples??[]).filter((e:any)=>e.gallery?.enabled).length+records.filter(r=>r.kind==='gallery').length;
const coverage={schemaVersion:1,docs:{total:(redirects.legacyDocuments??[]).length,indexed:count('doc')+count('changelog')},apiSymbols:{total:(api.symbols??[]).length,indexed:count('api-symbol')},apiOptions:{total:optionTotal,indexed:count('api-option')},apiTypes:{total:(api.types??[]).length,indexed:count('api-type')},examples:{total:(examples.examples??[]).length,indexed:count('example')},galleryMetadata:{total:allGalleryItemsForDocs.length,accounted:galleryAccounted},headings:count('heading'),errors:count('error')+count('diagnostic'),records:records.length};
for(const k of ['docs','apiSymbols','apiOptions','apiTypes','examples'] as const)if(coverage[k].total!==coverage[k].indexed)throw new Error(`[doc6] coverage mismatch ${k}`);
if(coverage.galleryMetadata.total!==coverage.galleryMetadata.accounted)throw new Error('[doc6] Gallery coverage mismatch');

const filterVerification={schemaVersion:1,runtimes:uniq(records.flatMap(r=>r.runtime)).sort(),packages:uniq(records.flatMap(r=>r.packages)).sort(),kinds:uniq(records.map(r=>r.kind)).sort(),stabilities:uniq(records.map(r=>r.stability)).sort(),versions:uniq(records.map(r=>r.version)).sort(),domains:uniq(records.map(r=>r.domain)).sort(),futurePackagesExposedAsCurrent:uniq(records.flatMap(r=>r.packages)).filter(p=>p!==api.package.name)};
if(filterVerification.futurePackagesExposedAsCurrent.length)throw new Error(`[doc6] future packages exposed: ${filterVerification.futurePackagesExposedAsCurrent.join(',')}`);
const canonicalVerification={schemaVersion:1,missingCanonicalHref:records.filter(r=>!r.canonicalHref).map(r=>r.id),duplicateCanonicalRecords:records.filter((r,i)=>records.findIndex(x=>x.id===r.id&&x.canonicalHref===r.canonicalHref)!==i).map(r=>r.id)};

const symbol=records.find(r=>r.kind==='api-symbol'),option=records.find(r=>r.kind==='api-option'),diag=records.find(r=>r.errorCode);
const cases:any[]=[{category:'symbol',query:symbol?.title,applicable:Boolean(symbol),expectedId:symbol?.id},{category:'option',query:option?.title,applicable:Boolean(option),expectedId:option?.id},{category:'concept',query:'canvas',applicable:true,expectedAny:true},{category:'goal',query:'create canvas',applicable:true,expectedAny:true},{category:'runtime',query:'node',applicable:true,expectedAny:true},{category:'package',query:api.package.name,applicable:true,expectedAny:true},{category:'error-code',query:diag?.errorCode??null,applicable:Boolean(diag),expectedId:diag?.id,reason:diag?undefined:'No public current error code'}];
for(const c of cases){if(!c.applicable){c.pass=null;continue;}const rs=searchRecords(index,records,c.query,{},20).results;c.actualTopIds=rs.slice(0,5).map(r=>r.id);c.pass=c.expectedId?rs[0]?.id===c.expectedId:rs.length>0;if(!c.pass)throw new Error(`[doc6] completion query failed ${c.category}`);}
const completion={schemaVersion:1,categories:cases,passedApplicable:cases.filter(c=>c.applicable).every(c=>c.pass===true),errorCodeApplicable:Boolean(diag)};

const canonicalDoc=new Map(records.filter(r=>r.kind==='doc'||r.kind==='changelog').map(r=>[r.canonicalHref.replace(/^\/docs\//,''),r.id]));
const explicit=new Map<string,string[]>((docs.pages??[]).map((p:any)=>[`doc:${p.id}`,p.related??[]]));
const related:any[]=[];
for(const src of records.filter(r=>['doc','changelog','api-symbol','api-member','example'].includes(r.kind))){const scored:any[]=[];for(const dst of records){if(src.id===dst.id||dst.kind==='heading')continue;if(src.stability==='CURRENT'&&['ROADMAP','REMOVED'].includes(dst.stability??''))continue;let score=0;const reasons:string[]=[];if(src.packages.some(x=>dst.packages.includes(x))){score+=2;reasons.push('same package')}if(src.runtime.some(x=>dst.runtime.includes(x))){score+=2;reasons.push('same runtime')}if(src.domain&&src.domain===dst.domain){score+=4;reasons.push('same domain')}const shared=src.keywords.filter(x=>dst.keywords.includes(x));if(shared.length){score+=Math.min(12,shared.length*3);reasons.push(`shared keywords: ${shared.slice(0,3).join(', ')}`)}const ex=explicit.get(src.id)??[];if(ex.some(s=>dst.canonicalHref===`/docs/${s}`||canonicalDoc.get(s)===dst.id)){score+=50;reasons.unshift('explicit related metadata')}if(src.kind==='example'&&dst.kind.startsWith('api-')&&src.keywords.some(k=>normalizeSearchText(k)===normalizeSearchText(dst.title))){score+=35;reasons.unshift('example API linkage')}if(score>=8)scored.push({id:dst.id,score,reasons});}scored.sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));related.push({sourceId:src.id,targets:scored.slice(0,6)});}
const relatedCoverage={schemaVersion:1,sourceRecords:related.length,withGeneratedTargets:related.filter(x=>x.targets.length).length,withoutGeneratedTargets:related.filter(x=>!x.targets.length).map(x=>x.sourceId),selfLinks:related.flatMap(x=>x.targets.filter((t:any)=>t.id===x.sourceId)).length,duplicateTargets:related.flatMap(x=>{const ys=x.targets.map((t:any)=>t.id);return ys.filter((id:string,i:number)=>ys.indexOf(id)!==i)}).length};
const publicCodes=records.filter(r=>r.errorCode).map(r=>({id:r.id,errorCode:r.errorCode,href:r.href}));
const diagnostic={schemaVersion:1,recordKind:'error | diagnostic',fields:['id','title','description','href','canonicalHref','runtime','packages','stability','errorCode','keywords','sourceId'],lookupKeys:['errorCode','title','related API symbol','runtime','package'],publicCurrentCodes:publicCodes.map(x=>({id:x.id,code:x.errorCode,href:x.href})),fabricatedCodes:[],futureCompatible:true};
const recordsText=stable({schemaVersion:SEARCH_SCHEMA_VERSION,sourceChecksum,records}),indexText=stable(index);
const size={schemaVersion:1,records:records.length,recordsRawBytes:Buffer.byteLength(recordsText),indexRawBytes:Buffer.byteLength(indexText),combinedRawBytes:Buffer.byteLength(recordsText)+Buffer.byteLength(indexText),delivery:'server-side generated index; clients fetch only bounded result JSON on interaction',eagerFullIndexOnOrdinaryDocsRoutes:false};
const sourceManifest={schemaVersion:1,docsStartSha:START,package:{name:api.package.name,version:api.package.version,commit:api.package.commit},sources:sourceFiles,gallery:{registryCount:allGalleryItemsForDocs.length,dataSha256:gallerySha},sourceChecksum};
const ranking={schemaVersion:1,priority:['exact symbol','exact error code','exact title','exact option','exact type','exact alias','package','runtime','title prefix','option/type','heading','goal','keyword','title/description','body','token','fuzzy'],stabilityPenalties:{REMOVED:-35,ROADMAP:-30,DEPRECATED:-18,EXPERIMENTAL:-6,PREVIEW:-3,CURRENT:0},deterministicTieBreak:['score desc','title asc','canonicalHref asc','id asc'],fuzzyMayOutrankExact:false};
const rankingVerification={schemaVersion:1,exactSymbolTop:symbol?searchRecords(index,records,symbol.title,{},5).results[0]?.id===symbol.id:null,exactOptionTop:option?searchRecords(index,records,option.title,{},5).results[0]?.id===option.id:null,completionMatrixPass:completion.passedApplicable};
const dependency={schemaVersion:1,addedRuntimeDependencies:[],addedDevDependencies:[],externalSearchServices:[],aiDependencies:[],indexRuntime:'first-party deterministic TypeScript'};

write('identity.json',{schemaVersion:1,phase:'DOC-6',startingDocsSha:START,packageMainSha:api.package.commit,packageVersion:api.package.version,phase14PFrozenSha:PHASE14P});
write('source-manifests.json',sourceManifest);write('search-records.json',{schemaVersion:SEARCH_SCHEMA_VERSION,sourceChecksum,records});write('search-index-manifest.json',index);write('search-coverage.json',coverage);write('ranking-rules.json',ranking);write('ranking-verification.json',rankingVerification);write('completion-query-matrix.json',completion);write('filter-verification.json',filterVerification);write('canonical-link-verification.json',canonicalVerification);write('related-content.json',{schemaVersion:1,records:related});write('related-content-coverage.json',relatedCoverage);write('diagnostic-contract.json',diagnostic);write('index-size.json',size);write('dependency-audit.json',dependency);write('search-source-checksums.json',{schemaVersion:1,files:sourceFiles,galleryDataSha256:gallerySha,combinedSha256:sourceChecksum});
write('index.json',{schemaVersion:1,phase:'DOC-6',files:['identity.json','source-manifests.json','search-records.json','search-index-manifest.json','search-coverage.json','ranking-rules.json','ranking-verification.json','completion-query-matrix.json','filter-verification.json','canonical-link-verification.json','related-content.json','related-content-coverage.json','diagnostic-contract.json','index-size.json','dependency-audit.json','search-source-checksums.json']});
console.log(`[doc6] ${CHECK?'verified':'generated'} ${records.length} records; source ${sourceChecksum.slice(0,12)}`);
