import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { DocsShell } from '@/components/docs/shell/DocsShell';
import { buildDocumentationNavigation } from '@/lib/docs/navigation';
import { loadDocumentationPages } from '@/lib/docs/content';
import { allApiRouteParams, apiSymbolByRoute, getApiManifest } from '@/lib/api-reference/manifest';
import { getExamplesForApiId } from '@/lib/examples/manifest';
import { ApiMethodHeader, ApiSignature, ErrorReference, LimitReference, OptionTable, Parameters, RelatedApiGrid, ReturnValue, TypesSection } from '@/components/api-reference/ApiReferenceComponents';

const SITE_ORIGIN='https://apexifyjs.vercel.app';
export const dynamicParams=false;
export function generateStaticParams(){return allApiRouteParams();}
export function generateMetadata({params}:{params:{package:string;symbol:string[]}}):Metadata{const found=apiSymbolByRoute(params.package,params.symbol);if(!found)return{title:'API not found | Apexify.js',robots:{index:false,follow:false}};const item=found.member||found.symbol;const canonical=`${SITE_ORIGIN}${item.href}`;return{title:`${found.member?`${found.member.owner}.${found.member.name}`:found.symbol.symbol} | Apexify.js API`,description:item.summary,alternates:{canonical},robots:{index:!['ROADMAP','REMOVED'].includes(item.stability),follow:true},openGraph:{type:'article',title:found.member?`${found.member.owner}.${found.member.name}`:found.symbol.symbol,description:item.summary,url:canonical,siteName:'Apexify.js Documentation'}};}
export default function ApiReferenceRoute({params}:{params:{package:string;symbol:string[]}}){const found=apiSymbolByRoute(params.package,params.symbol);if(!found)notFound();const manifest=getApiManifest();const groups=buildDocumentationNavigation(loadDocumentationPages());const lookup=new Map<string,{href:string;label:string;summary:string}>();for(const symbol of manifest.symbols){lookup.set(symbol.id,{href:symbol.href,label:symbol.symbol,summary:symbol.summary});for(const m of symbol.members)lookup.set(m.id,{href:m.href,label:`${m.owner}.${m.name}`,summary:m.summary});}const item=found.member||found.symbol;const errors=found.member?manifest.errors.filter(e=>e.relatedApiIds.includes(found.member!.id)):[];const limits=found.member?manifest.limits.filter(l=>l.id.startsWith(`${found.member!.id}::limit::`)):[];const options=found.member?(found.member.overloads[0]?.parameters.flatMap(p=>p.options)||[]):[];const doc5Examples=getExamplesForApiId(item.id);return <DocsShell groups={groups} headings={[]} activePath={item.href}><article className="apx-doc-prose apx-api-page" data-doc4-route={item.id} tabIndex={-1}><nav aria-label="API breadcrumbs" className="apx-api-breadcrumbs"><a href="/api-reference">API Reference</a><span>/</span><a href={found.symbol.href}>{found.symbol.symbol}</a>{found.member?<><span>/</span><span aria-current="page">{found.member.name}</span></>:null}</nav><ApiMethodHeader symbol={found.symbol} member={found.member}/><ApiSignature symbol={found.symbol} member={found.member}/>{found.member?<><Parameters member={found.member}/>{options.length?<><h2 id="api-options-heading">Options</h2><OptionTable options={options} ownerLabel={`${found.member.owner}.${found.member.name}`}/></>:null}<TypesSection member={found.member}/><ReturnValue member={found.member}/><ErrorReference errors={errors}/><LimitReference limits={limits}/></>:(found.symbol.members.length?<section><h2>Members</h2><div className="apx-api-related-grid">{found.symbol.members.map(m=><a className="apx-api-reference-card" key={m.id} href={m.href}><strong>{m.name}</strong><span>{m.kind}</span><p>{m.summary}</p></a>)}</div></section>:null)}<RelatedApiGrid ids={item.relatedApiIds} lookup={lookup}/>{doc5Examples.length?<section data-doc5-api-examples><h2>Verified examples</h2><div className="apx-api-related-grid">{doc5Examples.map(example=><a className="apx-api-reference-card" key={example.id} href={example.canonicalRoute}><strong>{example.title}</strong><span>DOC-5 · {example.runtime} · {example.difficulty} · verified</span><p>{example.summary}</p></a>)}</div></section>:null}{item.examples.length?<section><h2>Additional guides</h2><div className="apx-api-related-grid">{item.examples.map(e=><a className="apx-api-reference-card" key={e.id} href={e.href}><strong>{e.label}</strong><span>Existing documentation guide</span></a>)}</div></section>:null}</article></DocsShell>;}
