export type StudioProofRoute = 'browser' | 'full-runtime' | 'mixed' | 'contract-exclusion';
export type StudioArtifactProofKind = 'image' | 'gif' | 'audio' | 'video' | 'json' | 'text' | 'binary';

export type StudioExecutionProofCase = {
  id: string;
  title: string;
  route: StudioProofRoute;
  exactCapabilities?: readonly string[];
  capabilityPrefixes?: readonly string[];
  templateIds: readonly string[];
  optionFamilies: readonly string[];
  expectedArtifacts: readonly StudioArtifactProofKind[];
  staticEvidence: readonly string[];
  finalValidation: 'deferred-final-validation' | 'not-required';
};

export const STUDIO_EXECUTION_PROOF_CASES: readonly StudioExecutionProofCase[] = [
  {
    id: 'web-raster-core',
    title: '@apexify/web raster core',
    route: 'browser',
    exactCapabilities: [
      'ApexPainter.createCanvas',
      'ApexPainter.createImage',
      'ApexPainter.createText',
    ],
    templateIds: ['editorial-card', 'gradient-sunset', 'integration-showcase', 'framed-card'],
    optionFamilies: [
      'canvas color/gradient/transparent backgrounds',
      'background layers, patterns and noise',
      'canvas stroke, shadow and radius',
      'shape and bitmap image layers',
      'text font/fill/alignment/width',
      'Studio virtual image/font assets',
    ],
    expectedArtifacts: ['image'],
    staticEvidence: [
      'packages/web/src/studio-preview.ts in the pinned Apexify.js @apexify/web source snapshot',
      'components/studio/CodeStudio.tsx',
      'lib/studio/runtime/assets.ts',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'charts',
    title: 'Chart families and chart-buffer composition',
    route: 'mixed',
    exactCapabilities: [
      'ApexPainter.createChart',
      'ApexPainter.createComparisonChart',
      'ApexPainter.createComboChart',
    ],
    templateIds: ['integration-showcase'],
    optionFamilies: [
      'pie/doughnut',
      'bar',
      'horizontalBar',
      'line',
      'scatter',
      'radar',
      'polarArea',
      'comparison',
      'combo',
      'chart output reused as an image source',
    ],
    expectedArtifacts: ['image'],
    staticEvidence: [
      'packages/web/src/studio-preview.ts chart renderer in the pinned @apexify/web snapshot',
      'lib/studio/runtime/capabilities.ts full-runtime routing for comparison/combo charts',
      'lib/studio/studioConfig.ts integration-showcase',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'scene-builder',
    title: 'Scenes, SceneBuilder, nested surfaces and components',
    route: 'full-runtime',
    exactCapabilities: [
      'ApexPainter.createScene',
      'ApexPainter.renderScene',
      'ApexPainter.validateSceneRenderInput',
    ],
    capabilityPrefixes: ['SceneBuilder.', 'ApexPainter.components.'],
    templateIds: ['scene-components-assets'],
    optionFamilies: [
      'scene background',
      'image/text/chart/path/surface layers',
      'nested surfaces',
      'builder add/replace/insert/remove/move lifecycle',
      'scene validation',
      'badge/progress/avatar/card/watermark components',
      'asset-ref resolution',
    ],
    expectedArtifacts: ['image', 'json'],
    staticEvidence: [
      'lib/studio/runtime/capabilities.ts',
      'lib/studio/studioConfig.ts scene-components-assets',
      'lib/studio/runtime/wrapStudioSnippetForRunner.ts',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'templates',
    title: 'TemplateHandle resolution and rendering',
    route: 'full-runtime',
    exactCapabilities: ['ApexPainter.createTemplate'],
    capabilityPrefixes: ['TemplateHandle.'],
    templateIds: ['template-named-assets'],
    optionFamilies: [
      'native placeholders',
      'placeholder defaults',
      'named assets',
      'overrides',
      'insertions',
      'render-input inspection',
      'final render',
    ],
    expectedArtifacts: ['image', 'json'],
    staticEvidence: [
      'lib/studio/studioConfig.ts template-named-assets',
      'lib/studio/runtime/capabilities.ts',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'measure-and-structured',
    title: 'Measurement and structured result inspection',
    route: 'full-runtime',
    exactCapabilities: [
      'ApexPainter.measureText',
      'ApexPainter.prepareForRender',
    ],
    templateIds: ['scene-components-assets', 'template-named-assets'],
    optionFamilies: [
      'text metrics',
      'deep asset-ref preprocessing',
      'scalar/object/array JSON artifacts',
    ],
    expectedArtifacts: ['json'],
    staticEvidence: [
      'lib/studio/runtime/wrapStudioSnippetForRunner.ts structured artifact collector',
      'components/studio/StudioArtifactPreview.tsx JSON/text preview',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'image-utils',
    title: 'Image utility facade',
    route: 'full-runtime',
    capabilityPrefixes: ['ApexPainter.image.'],
    templateIds: ['image-utils-parity'],
    optionFamilies: [
      'resize',
      'crop',
      'filters/effects',
      'blend/mask/gradient',
      'collage/stitch',
      'palette/color analysis/removal',
      'conversion/compression',
      'hex validation',
    ],
    expectedArtifacts: ['image', 'json', 'text'],
    staticEvidence: [
      'lib/studio/runtime/capabilities.ts image facet routing',
      'lib/studio/studioConfig.ts image-utils-parity',
      'lib/studio/runtime/wrapStudioSnippetForRunner.ts',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'geometry-pixels-detect',
    title: 'Path2D, pixels and hit detection',
    route: 'full-runtime',
    capabilityPrefixes: [
      'ApexPainter.path2d.',
      'ApexPainter.pixels.',
      'ApexPainter.detect.',
    ],
    templateIds: ['path-pixels-detect'],
    optionFamilies: [
      'Path2D command creation',
      'Path2D draw/custom line rendering',
      'pixel read/write/manipulation',
      'point color read/write',
      'path/region/any-region hit detection',
      'distance measurement',
    ],
    expectedArtifacts: ['image', 'json'],
    staticEvidence: [
      'lib/studio/studioConfig.ts path-pixels-detect',
      'lib/studio/runtime/capabilities.ts',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'assets',
    title: 'Named asset registry lifecycle',
    route: 'full-runtime',
    capabilityPrefixes: ['ApexPainter.assets.'],
    exactCapabilities: ['ApexPainter.prepareForRender'],
    templateIds: ['scene-components-assets', 'template-named-assets'],
    optionFamilies: [
      'image/font/palette/value registration',
      'explicit replacement',
      'typed unregister',
      'has/list/delete/clear',
      'dotted-path resolve',
      '$ref preprocessing',
      'Studio virtual asset materialization',
    ],
    expectedArtifacts: ['image', 'json'],
    staticEvidence: [
      'lib/studio/runtime/assets.ts',
      'lib/studio/runtime/wrapStudioSnippetForRunner.ts',
      'lib/studio/studioConfig.ts scene-components-assets',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'plugins',
    title: 'Plugin host and ApexPainter plugin installation',
    route: 'full-runtime',
    exactCapabilities: ['ApexPainter.use'],
    capabilityPrefixes: ['ApexPainter.plugins.'],
    templateIds: [],
    optionFamilies: [
      'inline plugin install',
      'installed dependency helper imports',
      'plugin API register/get/has/remove/list',
      'installed/pending lifecycle inspection',
      'transactional install rollback path',
    ],
    expectedArtifacts: ['json', 'text'],
    staticEvidence: [
      'lib/studio/runtime/capabilities.ts plugin routing',
      'app/api/gallery/run/route.ts installed dependency exposure',
      'lib/studio/runtime/wrapStudioSnippetForRunner.ts structured collector',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'batch-chain',
    title: 'Batch and chain composition',
    route: 'full-runtime',
    exactCapabilities: ['ApexPainter.batch', 'ApexPainter.chain'],
    templateIds: ['batch-chain-parity'],
    optionFamilies: [
      'multi-operation batch',
      'multi-output collection',
      'chain current-buffer propagation',
      'canvas/image/text chain operations',
    ],
    expectedArtifacts: ['image', 'json'],
    staticEvidence: [
      'lib/studio/studioConfig.ts batch-chain-parity',
      'lib/studio/runtime/wrapStudioSnippetForRunner.ts multi-output collector',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'output-local',
    title: 'Local output conversion facade',
    route: 'full-runtime',
    exactCapabilities: [
      'ApexPainter.toOutput',
      'ApexPainter.outPut',
      'ApexPainter.output.dataURL',
      'ApexPainter.output.base64',
      'ApexPainter.output.blob',
      'ApexPainter.output.arrayBuffer',
    ],
    templateIds: [],
    optionFamilies: [
      'data URL',
      'base64',
      'Blob',
      'ArrayBuffer',
      'legacy output aliases',
    ],
    expectedArtifacts: ['image', 'json', 'text', 'binary'],
    staticEvidence: [
      'lib/studio/runtime/capabilities.ts output facet routing',
      'lib/studio/runtime/wrapStudioSnippetForRunner.ts Blob/ArrayBuffer/data-URL collection',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'gif',
    title: 'GIF and scene-to-GIF execution',
    route: 'full-runtime',
    exactCapabilities: ['ApexPainter.createGIF', 'ApexPainter.renderSceneToGIF'],
    templateIds: ['gif-motion-card', 'scene-to-gif'],
    optionFamilies: [
      'buffer/data-url/attachment GIF output',
      'frame delay/repeat/quality',
      'scene composed frame',
      'animated image metadata',
    ],
    expectedArtifacts: ['gif', 'image', 'json'],
    staticEvidence: [
      'lib/studio/studioConfig.ts gif-motion-card and scene-to-gif',
      'lib/studio/runtime/media.ts GIF metadata',
      'components/studio/StudioArtifactPreview.tsx',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'animation',
    title: 'Animation frame generation',
    route: 'full-runtime',
    exactCapabilities: ['ApexPainter.animate'],
    templateIds: ['animate-frame-sequence'],
    optionFamilies: [
      'frame duration',
      'frame dimensions',
      'canvas frame backgrounds',
      'ordered frame collection',
    ],
    expectedArtifacts: ['image', 'json'],
    staticEvidence: [
      'lib/studio/studioConfig.ts animate-frame-sequence',
      'lib/studio/runtime/wrapStudioSnippetForRunner.ts frame collection metadata',
      'components/studio/StudioArtifactPreview.tsx frame rail',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'audio',
    title: 'Procedural audio families',
    route: 'full-runtime',
    exactCapabilities: [
      'ApexPainter.createAudio.presetNames',
      'ApexPainter.createAudio.listPresets',
      'ApexPainter.createAudio.synth',
      'ApexPainter.createAudio.custom',
      'ApexPainter.createAudio.preset',
      'ApexPainter.createAudio.sequence',
      'ApexPainter.createAudio.compose',
      'ApexPainter.createAudio.mix',
    ],
    templateIds: ['audio-preset', 'audio-synth-custom', 'audio-sequence-compose-mix'],
    optionFamilies: [
      'preset catalog and preset generation',
      'synth/custom oscillators',
      'ADSR/filter/pan/modulation/noise',
      'sequence events',
      'compose timeline clips',
      'mix inputs',
      'WAV metadata and playback',
    ],
    expectedArtifacts: ['audio', 'json'],
    staticEvidence: [
      'lib/studio/studioConfig.ts audio templates',
      'lib/studio/runtime/media.ts WAV metadata',
      'components/studio/StudioArtifactPreview.tsx audio player',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'video-top-level',
    title: 'Top-level video creation, probing and extraction',
    route: 'full-runtime',
    exactCapabilities: [
      'ApexPainter.createVideo',
      'ApexPainter.getVideoInfo',
      'ApexPainter.extractFrames',
      'ApexPainter.extractAllFrames',
      'ApexPainter.extractFrameAtTime',
      'ApexPainter.extractFrameByNumber',
      'ApexPainter.extractMultipleFrames',
      'ApexPainter.renderSceneToVideoFrames',
    ],
    capabilityPrefixes: ['ApexPainter.video.'],
    templateIds: ['video-from-frames', 'video-pipeline-roundtrip', 'scene-to-video'],
    optionFamilies: [
      'frames-to-video',
      'metadata/probe',
      'single/multiple/interval/all frame extraction',
      'PNG/JPEG frame output',
      'scene-to-video',
      'MP4/WebM artifact preview',
    ],
    expectedArtifacts: ['video', 'image', 'json'],
    staticEvidence: [
      'lib/studio/runtime/isolatedNodeExecutor.ts',
      'scripts/studio/media-process-proxy.mjs',
      'lib/studio/runtime/wrapStudioSnippetForRunner.ts',
      'components/studio/StudioArtifactPreview.tsx',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'video-pipeline',
    title: 'VideoPipeline retained edit stack',
    route: 'full-runtime',
    exactCapabilities: ['ApexPainter.videoPipeline'],
    capabilityPrefixes: ['VideoPipeline.'],
    templateIds: ['video-pipeline-roundtrip'],
    optionFamilies: [
      'source',
      'trim',
      'splice',
      'text overlays',
      'audio/procedural tracks',
      'layer upsert/remove/clear',
      'undo/redo',
      'snapshot/getLayers',
      'render presets',
    ],
    expectedArtifacts: ['video', 'json'],
    staticEvidence: [
      'lib/studio/studioConfig.ts video-pipeline-roundtrip',
      'scripts/studio/media-process-proxy.mjs',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'video-deep-operations',
    title: 'Reachable VideoStack operation services',
    route: 'full-runtime',
    capabilityPrefixes: [
      'VideoCreator.',
      'VideoOperations.',
      'VideoOperations.transcode.',
      'VideoOperations.merge.',
      'VideoOperations.overlays.',
      'VideoOperations.audio.',
      'VideoOperations.frames.',
      'VideoOperations.structure.',
      'VideoOperations.advanced.',
    ],
    templateIds: ['video-pipeline-roundtrip', 'video-from-frames'],
    optionFamilies: [
      'transcode/trim/audio extraction/speed/effects/rotate/crop/compress/fade/reverse',
      'volume/mute/normalize/color correction',
      'merge/split-screen',
      'watermark/picture-in-picture/text overlays',
      'audio mixing',
      'frame extraction/thumbnail/preview/create-from-frames',
      'segment replacement',
      'loop/scene detection/stabilize/freeze/export preset/LUT/transition',
      'operation info/codec/dispatch description',
    ],
    expectedArtifacts: ['video', 'audio', 'image', 'json', 'text'],
    staticEvidence: [
      'lib/studio/runtime/capabilities.ts video facet routing',
      'scripts/studio/media-process-proxy.mjs',
      'lib/studio/runtime/isolatedNodeExecutor.ts',
    ],
    finalValidation: 'deferred-final-validation',
  },
  {
    id: 'host-persistence-exclusion',
    title: 'Host persistence is outside the Studio contract',
    route: 'contract-exclusion',
    exactCapabilities: [
      'ApexPainter.save',
      'ApexPainter.saveMultiple',
      'ApexPainter.createAudio.save',
    ],
    templateIds: [],
    optionFamilies: ['host filesystem persistence'],
    expectedArtifacts: [],
    staticEvidence: [
      'lib/studio/runtime/capabilities.ts host-persistence detection',
      'components/studio/CodeStudio.tsx pre-execution contract rejection',
    ],
    finalValidation: 'not-required',
  },
  {
    id: 'external-transfer-exclusion',
    title: 'Credentialed third-party transfer is outside the Studio contract',
    route: 'contract-exclusion',
    exactCapabilities: ['ApexPainter.output.url'],
    templateIds: [],
    optionFamilies: ['Imgur credentialed public upload'],
    expectedArtifacts: [],
    staticEvidence: [
      'lib/studio/runtime/capabilities.ts external-service detection',
      'STUDIO_FULL_APEXIFY_EXECUTION_PLAN.md non-goals',
    ],
    finalValidation: 'not-required',
  },
];

export type StudioOptionFamilyProof = {
  id: string;
  capability: string;
  families: readonly string[];
  proofCaseIds: readonly string[];
};

export const STUDIO_OPTION_FAMILY_PROOFS: readonly StudioOptionFamilyProof[] = [
  {
    id: 'canvas-backgrounds',
    capability: 'ApexPainter.createCanvas',
    families: ['color', 'linear/radial gradients', 'background layers', 'patterns', 'noise', 'stroke/shadow/radius', 'transparent base'],
    proofCaseIds: ['web-raster-core'],
  },
  {
    id: 'image-sources',
    capability: 'ApexPainter.createImage',
    families: ['built-in shapes', 'remote browser image', 'Studio asset image', 'generated chart buffer', 'fit/alignment/radius/stroke/shadow'],
    proofCaseIds: ['web-raster-core', 'charts'],
  },
  {
    id: 'text',
    capability: 'ApexPainter.createText',
    families: ['font family/size', 'bold', 'fill', 'alignment/baseline', 'max width', 'uploaded browser font'],
    proofCaseIds: ['web-raster-core'],
  },
  {
    id: 'charts',
    capability: 'ApexPainter.createChart',
    families: ['pie/doughnut', 'bar', 'horizontalBar', 'line', 'scatter', 'radar', 'polarArea', 'comparison', 'combo'],
    proofCaseIds: ['charts'],
  },
  {
    id: 'scene',
    capability: 'ApexPainter.createScene',
    families: ['background', 'image/text/path/chart', 'nested surface', 'component layers', 'asset refs', 'builder mutation'],
    proofCaseIds: ['scene-builder'],
  },
  {
    id: 'templates',
    capability: 'ApexPainter.createTemplate',
    families: ['placeholders/defaults', 'asset refs', 'overrides', 'insertions', 'render input', 'render'],
    proofCaseIds: ['templates'],
  },
  {
    id: 'image-utils',
    capability: 'ApexPainter.image',
    families: ['geometry', 'filters/effects', 'blend/mask', 'palette/color', 'conversion/compression', 'collage/stitch'],
    proofCaseIds: ['image-utils'],
  },
  {
    id: 'path-pixels-detect',
    capability: 'ApexPainter.path2d/pixels/detect',
    families: ['path commands', 'path drawing', 'pixel read/write', 'pixel transforms', 'hit regions', 'distance'],
    proofCaseIds: ['geometry-pixels-detect'],
  },
  {
    id: 'audio',
    capability: 'ApexPainter.createAudio',
    families: ['preset', 'synth', 'custom', 'sequence', 'compose', 'mix', 'metadata/playback'],
    proofCaseIds: ['audio'],
  },
  {
    id: 'video',
    capability: 'ApexPainter.video',
    families: ['creation/transcode', 'pipeline', 'metadata', 'frames', 'overlays', 'audio', 'structure', 'advanced operations', 'scene video'],
    proofCaseIds: ['video-top-level', 'video-pipeline', 'video-deep-operations'],
  },
  {
    id: 'structured',
    capability: 'structured/non-raster results',
    families: ['scalar', 'JSON object/array', 'typed arrays', 'ArrayBuffer', 'Blob', 'data URL', 'multi-output'],
    proofCaseIds: ['measure-and-structured', 'output-local', 'batch-chain'],
  },
];

export function proofCasesForCapability(capability: string): StudioExecutionProofCase[] {
  return STUDIO_EXECUTION_PROOF_CASES.filter((proof) => {
    if (proof.exactCapabilities?.includes(capability)) return true;
    return proof.capabilityPrefixes?.some((prefix) => capability.startsWith(prefix)) ?? false;
  });
}
