'use client';
import { useEffect,useMemo,useRef,useState,type PointerEvent as ReactPointerEvent } from 'react';
import { useStudioSharedSession } from '@/components/studio/StudioSharedSession';
import { StudioModeSwitch,type StudioMode } from '@/components/studio/StudioModeSwitch';
import { createVisualId } from '@/lib/studio/visual/ids';
import { createVisualNode,createVisualProject } from '@/lib/studio/visual/project';
import { generateVisualProjectCode } from '@/lib/studio/visual/codegen/generator';
import { downloadVisualProject,loadVisualProjectFile } from '@/lib/studio/visual/persistence';
import type { VisualProject,VisualTransform } from '@/lib/studio/visual/model';
import { VisualHistory,alignNodes,deleteNodes,duplicateNodes,moveNodes,nodeRect,patchNodeTransform,reorderNode,resizeNode,rotateNode,setNodeLocked,setNodeVisibility,setSelection,snapPosition,toggleSelection,type ResizeHandle } from '@/lib/studio/visual/editor';

type Props={active:boolean;mode:StudioMode;onModeChange:(mode:StudioMode)=>void};
type Gesture={kind:'move'|'resize'|'rotate'|'pan';id?:string;handle?:ResizeHandle;startX:number;startY:number;before:VisualProject;originPan?:{x:number;y:number};origin?:{x:number;y:number};center?:{x:number;y:number}};

const handles:ResizeHandle[]=['nw','n','ne','e','se','s','sw','w'];
const handlePos:Record<ResizeHandle,{left:string;top:string;cursor:string}>={nw:{left:'0%',top:'0%',cursor:'nwse-resize'},n:{left:'50%',top:'0%',cursor:'ns-resize'},ne:{left:'100%',top:'0%',cursor:'nesw-resize'},e:{left:'100%',top:'50%',cursor:'ew-resize'},se:{left:'100%',top:'100%',cursor:'nwse-resize'},s:{left:'50%',top:'100%',cursor:'ns-resize'},sw:{left:'0%',top:'100%',cursor:'nesw-resize'},w:{left:'0%',top:'50%',cursor:'ew-resize'}};

export default function VisualStudioPhase3({active,mode,onModeChange}:Props){
 const {setCodeHandoff}=useStudioSharedSession();
 const [project,setProject]=useState(()=>createVisualProject());
 const [zoom,setZoom]=useState(78),[pan,setPan]=useState({x:0,y:0}),[viewportMode,setViewportMode]=useState<'select'|'pan'>('select');
 const [message,setMessage]=useState('Phase 3 editor ready'),[historyTick,setHistoryTick]=useState(0),[guides,setGuides]=useState<Array<{axis:'x'|'y';value:number}>>([]);
 const history=useRef(new VisualHistory(100));const gesture=useRef<Gesture|null>(null);const fileRef=useRef<HTMLInputElement>(null);
 const selected=project.editor?.selectedNodeIds??[];const primary=selected.length?project.document.nodes[selected[selected.length-1]]:undefined;
 const generated=useMemo(()=>{try{return{value:generateVisualProjectCode(project),error:null}}catch(e){return{value:null,error:e instanceof Error?e.message:'Code generation unavailable'}}},[project]);
 const mutate=(label:string,fn:(p:VisualProject)=>VisualProject)=>setProject(current=>{const next=fn(current);history.current.commit(current,next,label);setHistoryTick(v=>v+1);return next});
 const addPlaceholder=()=>mutate('Add placeholder',p=>{const next=structuredClone(p);const node=createVisualNode('group',{}, {name:'Placeholder'});node.transform={x:80+next.document.rootNodeIds.length*24,y:80+next.document.rootNodeIds.length*24,width:180,height:110,rotation:0,opacity:1,visible:true,locked:false,zIndex:next.document.rootNodeIds.length};next.document.nodes[node.id]=node;next.document.rootNodeIds.push(node.id);next.editor={...next.editor,selectedNodeIds:[node.id]};return next;});
 const undo=()=>{const result=history.current.undo(project);if(result){setProject(result.project);setMessage('Undo: '+result.label);setHistoryTick(v=>v+1)}};
 const redo=()=>{const result=history.current.redo(project);if(result){setProject(result.project);setMessage('Redo: '+result.label);setHistoryTick(v=>v+1)}};
 const fit=()=>{setZoom(Math.max(20,Math.min(100,Math.floor(700/project.document.height*100))));setPan({x:0,y:0})};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const target=e.target as HTMLElement|null;if(target?.matches('input,textarea,[contenteditable=true]'))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();mutate('Duplicate',p=>duplicateNodes(p,selected,()=>createVisualId('node')));return}if((e.key==='Delete'||e.key==='Backspace')&&selected.length){e.preventDefault();mutate('Delete',p=>deleteNodes(p,selected));return}if(selected.length&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?10:1;mutate('Nudge',p=>moveNodes(p,selected,e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0));}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)});
 const beginMove=(e:ReactPointerEvent,id:string)=>{if(viewportMode!=='select')return;e.stopPropagation();const node=project.document.nodes[id];if(node?.transform?.locked)return;const next=e.shiftKey?toggleSelection(project,id):selected.includes(id)?project:setSelection(project,[id]);if(next!==project)setProject(next);const r=nodeRect(node);gesture.current={kind:'move',id,startX:e.clientX,startY:e.clientY,before:next,origin:{x:r.x,y:r.y}};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)};
 const beginResize=(e:ReactPointerEvent,id:string,handle:ResizeHandle)=>{e.stopPropagation();gesture.current={kind:'resize',id,handle,startX:e.clientX,startY:e.clientY,before:project};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)};
 const beginRotate=(e:ReactPointerEvent,id:string)=>{e.stopPropagation();const r=nodeRect(project.document.nodes[id]);const rect=(e.currentTarget.parentElement as HTMLElement).getBoundingClientRect();gesture.current={kind:'rotate',id,startX:e.clientX,startY:e.clientY,before:project,center:{x:rect.left+rect.width/2,y:rect.top+rect.height/2}};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)};
 const pointerMove=(e:ReactPointerEvent)=>{const g=gesture.current;if(!g)return;if(g.kind==='pan'&&g.originPan){setPan({x:g.originPan.x+e.clientX-g.startX,y:g.originPan.y+e.clientY-g.startY});return}if(!g.id)return;const scale=zoom/100,dx=(e.clientX-g.startX)/scale,dy=(e.clientY-g.startY)/scale;if(g.kind==='move'&&g.origin){const snap=snapPosition(g.before,g.id,g.origin.x+dx,g.origin.y+dy);setGuides(snap.guides);setProject(patchNodeTransform(g.before,g.id,{x:snap.x,y:snap.y}));}if(g.kind==='resize'&&g.handle)setProject(resizeNode(g.before,g.id,g.handle,dx,dy,e.shiftKey));if(g.kind==='rotate'&&g.center){const angle=Math.atan2(e.clientY-g.center.y,e.clientX-g.center.x)*180/Math.PI+90;setProject(rotateNode(g.before,g.id,e.shiftKey?Math.round(angle/15)*15:angle));}};
 const pointerUp=()=>{const g=gesture.current;if(!g)return;if(g.kind!=='pan'){history.current.commit(g.before,project,g.kind==='move'?'Move':g.kind==='resize'?'Resize':'Rotate');setHistoryTick(v=>v+1)}gesture.current=null;setGuides([])};
 const updateTransform=(key:keyof VisualTransform,value:number)=>{if(!primary)return;mutate('Transform '+String(key),p=>patchNodeTransform(p,primary.id,{[key]:value}))};
 const load=async(file:File)=>{try{const p=await loadVisualProjectFile(file);setProject(p);setZoom(Math.round((p.editor?.zoom??.78)*100));setPan({x:p.editor?.panX??0,y:p.editor?.panY??0});history.current=new VisualHistory(100);setMessage('Project loaded')}catch(e){setMessage(e instanceof Error?e.message:'Load failed')}};
 const save=()=>downloadVisualProject({...project,updatedAt:new Date().toISOString(),editor:{...project.editor,zoom:zoom/100,panX:pan.x,panY:pan.y}});
 const handoff=()=>{if(!generated.value){setMessage(generated.error??'Code unavailable');return}setCodeHandoff({id:createVisualId('handoff'),name:project.name+' — Generated',source:generated.value.source});onModeChange('code')};
 return <div className="apx-visual-workspace" data-active={active?'true':'false'}>
  <header className="apx-vw-header"><div className="apx-vw-brand"><span className="apx-vw-brandmark">A</span><span><strong>Visual Workspace</strong><small>Viewport · Layers · Transforms · History</small></span></div><StudioModeSwitch mode={mode} onChange={onModeChange} className="studio-mode-switch--visualbar"/><div className="apx-vw-header-actions"><button className="apx-vw-action" onClick={undo} disabled={!history.current.canUndo}>Undo</button><button className="apx-vw-action" onClick={redo} disabled={!history.current.canRedo}>Redo</button><button className="apx-vw-action" onClick={save}>Save</button><button className="apx-vw-action" onClick={()=>fileRef.current?.click()}>Load</button><input ref={fileRef} hidden type="file" accept=".apexstudio.json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)void load(f)}}/><button className="apx-vw-action" onClick={handoff} disabled={!generated.value}>Code</button></div></header>
  <div className="apx-vw-layout">
   <nav className="apx-vw-toolrail"><button className="apx-vw-tool" data-active={viewportMode==='select'?'true':undefined} onClick={()=>setViewportMode('select')}>↖<span>Select</span></button><button className="apx-vw-tool" data-active={viewportMode==='pan'?'true':undefined} onClick={()=>setViewportMode('pan')}>✋<span>Pan</span></button><button className="apx-vw-tool" onClick={addPlaceholder}>＋<span>Node</span></button></nav>
   <aside className="apx-vw-layers"><div className="apx-vw-panel-heading"><div><strong>Layers</strong><small>{project.document.rootNodeIds.length} nodes · {selected.length} selected</small></div><button className="apx-vw-iconbutton" onClick={addPlaceholder}>＋</button></div><div className="apx-vw-layer-tree">
    <div className="apx-vw-layer-row apx-vw-layer-row--root"><span>▾</span><span>Visual Project</span></div>
    {project.document.rootNodeIds.map((id,index)=>{const node=project.document.nodes[id],sel=selected.includes(id);return <div key={id} className="apx-vw-layer-row" data-active={sel?'true':undefined} onClick={e=>setProject(e.shiftKey?toggleSelection(project,id):setSelection(project,[id]))} style={{background:sel?'#17345a':undefined}}>
      <button title="Visibility" onClick={e=>{e.stopPropagation();mutate('Visibility',p=>setNodeVisibility(p,id,node.transform?.visible===false))}}>{node.transform?.visible===false?'○':'◉'}</button><button title="Lock" onClick={e=>{e.stopPropagation();mutate('Lock',p=>setNodeLocked(p,id,!node.transform?.locked))}}>{node.transform?.locked?'🔒':'◇'}</button><span style={{flex:1,overflow:'hidden',textOverflow:'ellipsis'}}>{node.name??node.kind}</span><button title="Move up" disabled={index===0} onClick={e=>{e.stopPropagation();mutate('Reorder',p=>reorderNode(p,id,index-1))}}>↑</button><button title="Move down" disabled={index===project.document.rootNodeIds.length-1} onClick={e=>{e.stopPropagation();mutate('Reorder',p=>reorderNode(p,id,index+1))}}>↓</button></div>})}
    {!project.document.rootNodeIds.length&&<div className="apx-vw-empty-list"><strong>No layers</strong><span>Add a generic placeholder to exercise Phase 3 editing infrastructure.</span></div>}
   </div><div className="apx-vw-mini-card"><strong>Layer actions</strong><span>Shift-click multi-select · Ctrl/Cmd+D duplicate · Delete remove · arrows nudge</span>{selected.length>0&&<div style={{display:'flex',gap:4,marginTop:6}}><button onClick={()=>mutate('Duplicate',p=>duplicateNodes(p,selected,()=>createVisualId('node')))}>Duplicate</button><button onClick={()=>mutate('Delete',p=>deleteNodes(p,selected))}>Delete</button></div>}</div></aside>
   <main className="apx-vw-stage"><div className="apx-vw-stagebar"><div className="apx-vw-device">Desktop ({project.document.width} × {project.document.height})</div><div className="apx-vw-zoom"><button onClick={()=>setZoom(v=>Math.max(20,v-10))}>−</button><span>{zoom}%</span><button onClick={()=>setZoom(v=>Math.min(200,v+10))}>+</button></div><div className="apx-vw-viewtools"><button onClick={()=>setZoom(100)}>100%</button><button onClick={fit}>Fit</button></div></div>
    <div className="apx-vw-viewport" onPointerDown={e=>{if(viewportMode==='pan'){gesture.current={kind:'pan',startX:e.clientX,startY:e.clientY,before:project,originPan:pan};e.currentTarget.setPointerCapture(e.pointerId)}else if(e.target===e.currentTarget)setProject(setSelection(project,[]))}} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onWheel={e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();setZoom(v=>Math.max(20,Math.min(200,v+(e.deltaY<0?5:-5))))}}}>
     <div className="apx-vw-artboard" style={{width:project.document.width,height:project.document.height,transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom/100})`,transformOrigin:'center'}}>
      <div className="apx-vw-artboard-grid"/>{guides.map((g,i)=><div key={i} style={{position:'absolute',zIndex:50,pointerEvents:'none',background:'#5aa7ff',...(g.axis==='x'?{left:g.value,top:0,bottom:0,width:1}:{top:g.value,left:0,right:0,height:1})}}/>)}
      {project.document.rootNodeIds.map(id=>{const node=project.document.nodes[id];if(node.transform?.visible===false)return null;const r=nodeRect(node),sel=selected.includes(id);return <div key={id} onPointerDown={e=>beginMove(e,id)} style={{position:'absolute',left:r.x,top:r.y,width:r.width,height:r.height,transform:`rotate(${node.transform?.rotation??0}deg)`,transformOrigin:'center',border:sel?'2px solid #5aa7ff':'1px solid #31557e',background:'linear-gradient(135deg,rgba(62,120,255,.16),rgba(122,82,242,.12))',boxSizing:'border-box',userSelect:'none',opacity:node.transform?.opacity??1}}>
       <span style={{position:'absolute',inset:0,display:'grid',placeItems:'center',fontSize:18,color:'#a9bfd7'}}>{node.name??node.kind}</span>
       {sel&&!node.transform?.locked&&handles.map(h=><button key={h} aria-label={'Resize '+h} onPointerDown={e=>beginResize(e,id,h)} style={{position:'absolute',left:handlePos[h].left,top:handlePos[h].top,width:10,height:10,borderRadius:2,border:'1px solid white',background:'#5aa7ff',transform:'translate(-50%,-50%)',cursor:handlePos[h].cursor,zIndex:5}}/>)}
       {sel&&!node.transform?.locked&&<button aria-label="Rotate" onPointerDown={e=>beginRotate(e,id)} style={{position:'absolute',left:'50%',top:-28,width:12,height:12,borderRadius:99,border:'1px solid white',background:'#9b7cff',transform:'translateX(-50%)',cursor:'grab'}}/>}
      </div>})}
     </div>
    </div>
   </main>
   <aside className="apx-vw-inspector"><div className="apx-vw-inspector-top"><span>Inspector</span></div><div className="apx-vw-inspector-tabs"><button data-active="true">Transform</button></div><div className="apx-vw-inspector-body">{primary?<><div className="apx-vw-inspector-title"><div><strong>{primary.name??primary.kind}</strong><small>{selected.length>1?selected.length+' selected':primary.id}</small></div></div><div className="apx-vw-fieldgrid">{(['x','y','width','height','rotation','opacity'] as const).map(k=><div key={k}><label>{k}</label><input className="apx-vw-field" type="number" step={k==='opacity'?0.05:1} value={k==='opacity'?(primary.transform?.opacity??1):(primary.transform?.[k]??(k==='width'?160:k==='height'?100:0))} onChange={e=>updateTransform(k,Number(e.target.value))}/></div>)}</div><div className="apx-vw-inspector-note">Resize with handles. Shift preserves aspect ratio / 15° rotation. Locked nodes cannot transform.</div>{selected.length>1&&<><div className="apx-vw-fieldgroup" style={{marginTop:12}}><label>Align / distribute</label><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:4}}>{(['left','center','right','top','middle','bottom','distribute-horizontal','distribute-vertical'] as const).map(a=><button key={a} onClick={()=>mutate('Align '+a,p=>alignNodes(p,selected,a))}>{a.replace('distribute-','dist ')}</button>)}</div></div></>}</>:<div className="apx-vw-empty-list"><strong>No selection</strong><span>Select a layer or object to edit numeric transforms.</span></div>}</div></aside>
   <section className="apx-vw-dock"><div className="apx-vw-dock-tabs"><span className="apx-vw-dock-label">History</span></div><div className="apx-vw-dock-content" style={{gridTemplateColumns:'1fr'}}><div className="apx-vw-dock-primary"><div className="apx-vw-history-list">{history.current.entries.length?history.current.entries.slice(0,12).map((x,i)=><div className="apx-vw-history-row" key={i}><span>↶</span><strong>{x}</strong><span>{i===0?'latest':''}</span></div>):<div className="apx-vw-dock-empty"><strong>No editor history yet</strong><span>Semantic edits are grouped into undoable commands.</span></div>}</div></div></div></section>
  </div>
  <footer className="apx-vw-statusbar"><span>Apexify Studio Visual</span><span className="apx-vw-status-ok">● STUDIO-VISUAL-3 editor</span><span>{message}</span><span className="ml-auto">{generated.error?'Codegen: owning authoring phase pending':'Codegen ready'} · history {historyTick}</span></footer>
 </div>
}
