'use client';
import type { InputHTMLAttributes,ReactNode,SelectHTMLAttributes } from 'react';
function Frame({id,label,description,error,children}:{id:string;label:string;description?:string;error?:string;children:ReactNode}){return <div className="grid gap-1.5"><label htmlFor={id} className="text-sm font-semibold" style={{color:'var(--text-primary)'}}>{label}</label>{description?<p id={`${id}-description`} className="text-xs" style={{color:'var(--text-tertiary)'}}>{description}</p>:null}{children}{error?<p id={`${id}-error`} role="alert" className="text-xs" style={{color:'var(--danger)'}}>{error}</p>:null}</div>}
export function TextField({id,label,description,error,...props}:{id:string;label:string;description?:string;error?:string}&InputHTMLAttributes<HTMLInputElement>){return <Frame {...{id,label,description,error}}><input {...props} id={id} type={props.type??'text'} aria-describedby={[description&&`${id}-description`,error&&`${id}-error`].filter(Boolean).join(' ')||undefined} aria-invalid={!!error} className="min-h-11 rounded-lg px-3" style={{border:'1px solid var(--border-default)',background:'var(--bg-raised)',color:'var(--text-primary)'}}/></Frame>}
export function NumberField(props:{id:string;label:string;description?:string;error?:string}&InputHTMLAttributes<HTMLInputElement>){return <TextField {...props} type="number"/>}
export function RangeField(props:{id:string;label:string;description?:string;error?:string}&InputHTMLAttributes<HTMLInputElement>){return <TextField {...props} type="range"/>}
export function ColorField(props:{id:string;label:string;description?:string;error?:string}&InputHTMLAttributes<HTMLInputElement>){return <TextField {...props} type="color"/>}
export function BooleanField({id,label,description,checked,onChange}:{id:string;label:string;description?:string;checked:boolean;onChange:(checked:boolean)=>void}){return <Frame {...{id,label,description}}><input id={id} type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="h-5 w-5"/></Frame>}
export function EnumField({id,label,description,error,options,...props}:{id:string;label:string;description?:string;error?:string;options:readonly {value:string;label:string}[]}&SelectHTMLAttributes<HTMLSelectElement>){return <Frame {...{id,label,description,error}}><select {...props} id={id} aria-invalid={!!error} className="min-h-11 rounded-lg px-3" style={{border:'1px solid var(--border-default)',background:'var(--bg-raised)',color:'var(--text-primary)'}}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></Frame>}
export function OptionGroup({title,children}:{title:string;children:ReactNode}){return <fieldset data-doc8-primitive="options" className="grid gap-3 rounded-lg p-3" style={{border:'1px solid var(--border-default)'}}><legend className="px-1 text-sm font-semibold">{title}</legend>{children}</fieldset>}
